network_id: fedn-test-networ
controller:
    discover_host: 192.168.2.235
    discover_port: 8090
    token: token 
 
combiner:
    name: Combiner_FEDN
    host: Combiner_FEDN
    port: 12080
    max_clients: 50
